site_name: JOJO Doc
nav:
    - Home: 'index.md'
    # - CodeTools:
    - Coding: 
      - Envs Setup: coding/envs.md
      - Configs: coding/configs.md
      - Python:
        - Pytorch: 'coding/python/pytorch.md'
        - Python tips: 'coding/python/tips.md'
        - Bitter Lessons: 'coding/python/bitter_lessons.md'
    - Cheatsheets:
      - Slurm: 'coding/cheatsheets/slurm.md'
      - Git: 'coding/cheatsheets/git.md'
      - Linux: 'coding/cheatsheets/linux.md'
      - Oh-my-zsh: 'coding/cheatsheets/ohmyzsh.md'
    - Research: 
      - Latex: 'research/latex.md'
      - Softwares: 'research/softwares.md'
      - Website: 'research/website.md'
# theme: material


# Configuration
theme:
  name: material
  # custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
